apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app1
  namespace: dev
  labels:
    name: deploy-app1
    type: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-app1
      type: app1
  template:
    metadata:
      name: pod-app1
      labels:
        app: pod-app1
        type: app1
    spec:
      containers:
        - name: app1
          image: app1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: app1-port
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
