apiVersion: v1
kind: Service
metadata:
  name: svc-app1
  namespace: dev
  labels:
    name: svc-app1
    type: app1
spec:
  type: NodePort
  selector:
    app: pod-app1
    type: app1
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30007
