apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app2
  namespace: dev
  labels:
    name: deploy-app2
    type: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-app2
      type: app2
  template:
    metadata:
      name: pod-app2
      labels:
        app: pod-app2
        type: app2
    spec:
      containers:
        - name: app2
          image: app2:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: cm-app2
          ports:
            - name: app2-port
              containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
