apiVersion: v1
kind: Service
metadata:
  name: svc-app2
  namespace: dev
  labels:
    name: svc-app2
    type: app2
spec:
  type: NodePort
  selector:
    app: pod-app2
    type: app2
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30008
