name: Test Workflow
on: 
  issue_comment:
    types: [created]
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get comments
        run: echo ${{ github.event.comment.body }}
