name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: fetch repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get git logs
        run: | 
          pwd
          ls
          git log --oneline
