name: Test Workflow
on: push
    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get comments
        run: |
            echo ${GITHUB_WORKSPACE}
            git diff origin/main HEAD --name-only
