name: Test Workflow
on: 
  pull_request_review:
    types: [submitted, edited]
    
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get comments
        run: echo ${{ github.event.comment.body }}
